server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  include /etc/nginx/mime.types;
  types { text/javascript mjs; application/wasm wasm; application/manifest+json webmanifest; }
  location = /sw.js { add_header Cache-Control "no-cache"; }
  location /models/ { add_header Cache-Control "public, max-age=604800"; }
  location / { add_header Cache-Control "no-cache"; try_files $uri $uri/ =404; }
}
